### ISSUE TITLE
Error: Cannot find module 'gpu.js'

### ISSUE THREAD

**Issue by DawnLck** [BrainJS/brain.js#104]
Sorry, but i cant find where this file at.

**Comment by s0kil** [comment]
https://github.com/gpujs/gpu.js

**Comment by robertleeplummerjr** [comment]
My bad. A missing dependency. I went ahead and added, and we should be set:
https://github.com/BrainJS/brain.js/blob/366cde6c8514be0dd0100b1ba93c8635158b0e96/package.json#L68

**Comment by robertleeplummerjr** [comment]
I believe this to be resolved.

**Comment by kenchambers** [comment]
i just downloaded the latest version `brain.js` from a `yarn add ` and i got this error @robertleeplummerjr

**Comment by kiro7shiro** [comment]
@robertleeplummerjr: I tried the gpu.html file from the examples directory and got the same error, too. "Uncaught TypeError: gpu_js is undefined" at brain.js:5460:13.

**Comment by tomosterlund** [comment]
I also keep getting this error, when downloading brain.js in the node:14 docker image.

Running `apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config` on building the image also doesn't solve the problem.

**Comment by rkaveski** [comment]
The same issue for me, added with `yarn add` @robertleeplummerjr

**Comment by 8keithkwok** [comment]
any solution for this?

**Comment by daviduhlir** [comment]
Still, the problem is, in built sources in index.js it's required by '../node_modules/gpu.js' ... which is not right, it should be only 'gpu.js' ... because it's peer dependency and after deduplication, it's only in root of node_modules ... if you are running on old npm without dedup, it's working correctly.
But this requirement is probably generated in this point

https://github.com/BrainJS/brain.js/blob/ddfa691d1ce3f6ff526e131007f292fa1d99f5b6/rollup.config.js#L17

edit: nasty workaround for me was to adding postinstall script in my project:
```
"postinstall": "sed -i '' 's/\\.\\.\\/node_modules\\/gpu\\.js\\/src\\/index.js/gpu\\.js/' ./node_modules/brain.js/dist/index.js"
```
it will replace whole path to gpu.js to only "gpu.js"

**Comment by WilliamKarolDiCioccio** [comment]
I know it might seem like a stack overflow question, but how can I do the same on windows batch?

**Comment by daviduhlir** [comment]
> I know it might seem like a stack overflow question, but how can I do the same on windows batch?

You will need to use powershell probably like this: https://stackoverflow.com/questions/46353836/how-to-execute-powershell-ps1-scripts-from-package-json-scripts

and then replace text in file by using command like this https://stackoverflow.com/questions/60034/how-can-you-find-and-replace-text-in-a-file-using-the-windows-command-line-envir

By solution is doing only replace string in file.

**Comment by robertleeplummerjr** [comment]
Please try https://www.npmjs.com/package/brain.js/v/2.0.0-beta.21, it should be resoled there.  I merged https://github.com/BrainJS/brain.js/pull/886 to achieve this.

**Comment by ASR4** [comment]
@robertleeplummerjr this did not help either
Still the same error: 
`Error: Cannot find module 'gpu.js'`

**Comment by daviduhlir** [comment]
you need to install it in your project as its only peer dependency. `npm i gpu.js --save` should solve it.

**Comment by html5-ninja** [comment]
> you need to install it in your project as its only peer dependency. `npm i gpu.js --save` should solve it.

work perfectly , thank you

**Comment by sumukhj1219** [comment]
npm i gpu.js --force  worked for  me  :)
