### ISSUE TITLE
Support node 13

### ISSUE THREAD

**Issue by vicary** [BrainJS/brain.js#476]
![A GIF or MEME to give some spice of the internet](https://i.giphy.com/media/VbnUQpnihPSIgIXuZv/giphy.webp)

## *What* is wrong?

Running examples generates a warning, my guess is that node 13 wants to go strict on differentiating cjs and mjs modules.

Terminal dump: 
```
node:37516) Warning: require() of ES modules is not supported.
require() of /Users/vicary/Desktop/node-test/node_modules/brain.js/src/index.js from /Users/vicary/Desktop/node-test/brain.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/vicary/Desktop/node-test/node_modules/brain.js/package.json.
```

## *Where* does it happen?

Wherever it runs `reuqire("brain.js")`

## *How* do we replicate the issue?

Just run the examples with the latest node version.

## *How* important is this (1-5)?

4?

## Expected behavior (i.e. solution)

No warnings are generated when an example is run.

## Other Comments
Falling back to node LTE (12.13.0) removes the warning.

**Comment by mubaidr** [comment]
Updated to support node 13, should be working fine now:  https://github.com/BrainJS/brain.js/commit/c85cc6a7fad3d79b259bfc9f3c5cf770d28e40da

**Comment by SalmonMoses** [comment]
> Updated to support node 13, should be working fine now: [c85cc6a](https://github.com/BrainJS/brain.js/commit/c85cc6a7fad3d79b259bfc9f3c5cf770d28e40da)

Still doesn't, sadly. Still throws the same error:
`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: c:\Coding\Labs\Node.JS\MochaTest\node_modules\brain.js\src\index.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:13)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (c:\Coding\Labs\Node.JS\MochaTest\index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14) {
  code: 'ERR_REQUIRE_ESM'
}`
NodeJS 13.2.0, no other packages installed except for Mocha and Brain.js

**Comment by mubaidr** [comment]
This version is not published yet.

**Comment by maxtomczyk** [comment]
Hi!
Is there any estimated date of update containing this fix?

**Comment by mubaidr** [comment]
Latest alpha versions have this option fixed.
