### ISSUE TITLE
Train imported model from JSON fails

### ISSUE THREAD

**Issue by jemmali-git** [BrainJS/brain.js#741]
Trying to train an imported model from JSON fails.

Use case:
```typescript
 let net = new LSTM();
      const trainingData = [
        {
          input: 'hi',
          output: 'mom',
        },
        {
          input: 'howdy',
          output: 'dad',
        },
        {
          input: 'hello',
          output: 'sis',
        },
        {
          input: 'yo',
          output: 'bro',
        },
      ];
      net.train(trainingData, { iterations: 20 });

      const net2 = new LSTM().fromJSON(net.toJSON());
      net2.train(trainingData, { iterations: 20 });
      net2.run('hi');
```
Error:
```
Error: Network error rate is unexpected NaN, check network configurations and try again.
 Most probably input format is not correct or training data is not enough. 

    at LSTM.train (brain.js\src\recurrent\rnn.ts:628:15)
```
Fix:
Setting dataFormatter.isSetup to true in DataFormatter.fromJSON solve the problem
```typescript
    dataFormatter.isSetup = true;
```
So is there any drawback for this Fix ?

**Comment by thxrben** [comment]
I am actually at this point too. Anything new?

**Comment by retrievaaaa** [comment]
Same problem. I store the model in a json, try to load it, but it just fails with the same error.

**Comment by robertleeplummerjr** [comment]
This has been resolved in https://www.npmjs.com/package/brain.js/v/2.0.0-beta.11.  Here is a working example: https://observablehq.com/@robertleeplummerjr/brain-js-issue-741.

**Comment by TejasQ** [comment]
This isn't solved. When trying to train the model after loading fromJSON, it still fails as they describe in the issue:

![image](https://user-images.githubusercontent.com/9947422/179324449-2bf6f378-f702-4458-bffc-45c3983eacfb.png)

**Comment by TejasQ** [comment]
It's the same issue as #787

**Comment by robertleeplummerjr** [comment]
Thanks for reproducing.  I'll look at this early this week.

**Comment by cpgb85** [comment]
> Thanks for reproducing. I'll look at this early this week.

Any progress  on figuring this out? This is pretty much useless  without being able to save a previous network.

**Comment by bigclap** [comment]
https://observablehq.com/@bigclap/brain-js-issue-741
Wok's well  with this fix
