### ISSUE TITLE
Not possible to require or import?

### ISSUE THREAD

**Issue by embiem** [BrainJS/brain.js#80]
I switched to this maintained library from the old one. Just doing the switch, I am no longer able to use a standard `const brain = require('brain.js')` (I basically just changed from brain to brain.js in the require), because the module will not be exported but put on the global `window` variable.

Is there a reason for this? For now I just access the library using window.brain, but it would be nice to actually import/require the module to achieve a modern build process using e.g. webpack.

Any info on this and explanation why it is done this way would be nice.

//edit: I'm using brain inside the browser, I also tried `brain.js/browser` and it is also adding brain to window instead of exporting it.

**Comment by robertleeplummerjr** [comment]
Is this in the browser?

**Comment by embiem** [comment]
Yes

**Comment by robertleeplummerjr** [comment]
I will address this shortly, very good points being made here.

**Comment by michaelsanford** [comment]
Is the intention to go with the [ES6-style](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)
```
import { xxx } from brain;
```
?

That would be my humble recommendation, at least. This would presumably allow existing implementations of `require('brain.js')` that expect it to be attached to `window` not to break, at least for now.

To wit, are there cases in which the `browser` variant is called and there is _not_ an available `window`?

@robertleeplummerjr If you've not yet gotten around to it, I'd be interested in working on this.

**Comment by robertleeplummerjr** [comment]
I believe this is now resolved.
@michaelsanford the library uses (at least I looked) `import { xxx } from whatever;`, (src/neural-network.js, for example) but does not in `index.js` which gets files from `./dist`, which are es5.

If you'd like to use the es6 files, simply use `import brain from 'brain.js/src';` or `import brain from 'brain.js/src/index';` _I think_.

>@robertleeplummerjr If you've not yet gotten around to it, I'd be interested in working on this.

I didn't see that till it was too late.  Feel free to check the wiki, the direction, and any outstanding bugs.  Committers & forks are wanted and loved.

Ty!

**Comment by michaelsanford** [comment]
Sweet! Perfect timing.

And I'm happy to hear that: I'll definitely poke around this _most intriguing_ library. 👍

**Comment by robertleeplummerjr** [comment]
Just wait till you see what we have planned next.  Full on GPU power for web and node.

**Comment by robertleeplummerjr** [comment]
fiy: https://github.com/harthur-org/brain.js/tree/nn-gpu
It isn't like "we plan on doing this... someday" no, it is already running.  We just want to simplify it so that anyone can learn ai.

**Comment by embiem** [comment]
That's awesome! Thanks for fixing and very cool to see this library still being actively developed.

**Comment by robertleeplummerjr** [comment]
Thanks for helping us make it better

**Comment by jasonhargrove** [comment]
Sadly does not work using the `/src` solution described above. It throws an import error. (Using babel and webpack). Odd regression re something as simple as module loading.

#### Here's what works in `1.0.0-rc.3`:

```

  require('brain.js/browser.js');

```

This attaches brain to `window.brain`.

#### For those who use webpack, you'll get a complaint about a pre-built javascript file.

![image](https://user-images.githubusercontent.com/285708/31790099-53c51b82-b4e2-11e7-97ce-034f7455b4cb.png)

![image](https://user-images.githubusercontent.com/285708/31790214-bebc4776-b4e2-11e7-8e97-253a6d3f699a.png)

You can make the warning go away by adding `noParse` to your webpack config:

```
module: {
  noParse: [
    /node_modules\/brain.js\/browser.js/
  ],
  preLoaders: []
}
```

**Comment by jasonhargrove** [comment]
To aid those searching, the error we experienced that resulted from the upgrade is `TypeError: brain.NeuralNetwork is not a constructor`. (Because it's not loading properly anymore.)

**Comment by robertleeplummerjr** [comment]
webpack needs a node file, use: `require('brain.js');` I _think_ should fix it.

**Comment by robertleeplummerjr** [comment]
Did the above solution help at all?

**Comment by treyreynolds** [comment]
Hopefully, this is helpful if someone is reading this in the future: 

For the ES6 import to work I used: `import brain from 'brain.js/src/index';`

**Comment by robertleeplummerjr** [comment]
@jasonhargrove this should be resolved now, can you confirm?

**Comment by nadeeraka** [comment]
Module not found: Can't resolve 'brain.js' in react 
this can solve  importing brain js 
import  brain from 'brain.js/src/index'

**Comment by matthewjumpsoffbuildings** [comment]
When using in node, I'm still getting  `TypeError: brain.NeuralNetwork is not a constructor` when I  do
```js
const brain = require('brain.js')
const net = new brain.NeuralNetwork()
```
It turns out that, for some bizzare reason, the export from `brain.js` is this
```js
{
  brain: { ...brain class },
  default: { ...brain class again? }
}
```
So in order to get it working properly, you should do
```js
const brain = require('brain.js').brain // redundant access to nested object
const net = new brain.NeuralNetwork()
```

**Comment by matthewjumpsoffbuildings** [comment]
This is broken even on examples linked to on https://brain.js.org

At the very least the docs/guides should reflect this export structure, so people don't get so confused

**Comment by Jacksonmills** [comment]
Currently struggling with this as well, I am seeing the same as @matthewjumpsoffbuildings, even all examples are broken...

**Comment by robertleeplummerjr** [comment]
Working on this right now guys.  Sorry about the issue.

**Comment by robertleeplummerjr** [comment]
Just published https://www.npmjs.com/package/brain.js/v/2.0.0-beta.4

**Comment by grmatthews** [comment]
If this was meant to enable importing in React or similar, or if node type = 'module' then still broken....?

Most modules downloadable via npm allow for import based usage, e.g.

import { brain } from "brain.js"

or 

import * as brain from "brain.js"

Neither of these seem to work -- am using brain.js@2.0.0-beta.4

**Comment by p2426** [comment]
For browser based importing - it would seem like (on 2.0.0-beta.4) you can `import * as brain from 'brain.js/dist/brain-browser.js'`

**Comment by KokoDoko** [comment]
> For browser based importing - it would seem like (on 2.0.0-beta.4) you can `import * as brain from 'brain.js/dist/brain-browser.js'`

This doesn't seem to be working `Unable to resolve module 'brain.js/dist/brain-browser.js'`
