### ISSUE TITLE
net.run gives same response regardless of input

### ISSUE THREAD

**Issue by thegamecat** [BrainJS/brain.js#98]
I have a trained net that has an error of .06 (I've tested with an error of 0.0005) and when I do a netrun every single response is {"do":0.3964411059957613} regardless of what data is in input. 

Any ideas why?

**Comment by robertleeplummerjr** [comment]
Can I see source?  I need more context.

**Comment by thegamecat** [comment]
This is the stored nn:

{
  "layers": [
    {
      "ema20ema50percentage": {},
      "ema20ema100percentage": {},
      "ema20ema200percentage": {},
      "ema50ema100percentage": {},
      "ema50ema200percentage": {},
      "ema100ema200percentage": {}
    },
    {
      "0": {
        "bias": -1.5750287727890826,
        "weights": {
          "ema20ema50percentage": -20.25601029294507,
          "ema20ema100percentage": 0.45155990760160286,
          "ema20ema200percentage": 0.9709692038720795,
          "ema50ema100percentage": 20.639682793958684,
          "ema50ema200percentage": 19.975838224699498,
          "ema100ema200percentage": -1.4236833640338198
        }
      },
      "1": {
        "bias": 3.673306830993333,
        "weights": {
          "ema20ema50percentage": 30.770078299681398,
          "ema20ema100percentage": -5.425816420140965,
          "ema20ema200percentage": -4.227178255669408,
          "ema50ema100percentage": -36.613607664374,
          "ema50ema200percentage": -33.30627337398423,
          "ema100ema200percentage": 4.201335921604437
        }
      },
      "2": {
        "bias": 1.8227045570046092,
        "weights": {
          "ema20ema50percentage": 17.369191067278347,
          "ema20ema100percentage": -2.420666145569872,
          "ema20ema200percentage": -1.7769276688121898,
          "ema50ema100percentage": -20.369733465778662,
          "ema50ema200percentage": -18.42808116596809,
          "ema100ema200percentage": 2.3478189801860867
        }
      },
      "3": {
        "bias": 1.5185414425076638,
        "weights": {
          "ema20ema50percentage": 15.483940725383432,
          "ema20ema100percentage": -2.0763106966298435,
          "ema20ema200percentage": -1.5246698979511473,
          "ema50ema100percentage": -17.56431541365488,
          "ema50ema200percentage": -15.97979726318819,
          "ema100ema200percentage": 2.13326395858417
        }
      },
      "4": {
        "bias": 0.4936868611628317,
        "weights": {
          "ema20ema50percentage": 6.3115791503417835,
          "ema20ema100percentage": -1.1711360443374403,
          "ema20ema200percentage": -0.7587969952194097,
          "ema50ema100percentage": -7.486116663115731,
          "ema50ema200percentage": -6.933388787399845,
          "ema100ema200percentage": 0.7616011775875742
        }
      },
      "5": {
        "bias": -3.049950482066496,
        "weights": {
          "ema20ema50percentage": -36.35536423248331,
          "ema20ema100percentage": 3.073380700763092,
          "ema20ema200percentage": 1.2690096491588287,
          "ema50ema100percentage": 39.4939383526204,
          "ema50ema200percentage": 35.582929310791016,
          "ema100ema200percentage": -5.146388524528173
        }
      }
    },
    {
      "do": {
        "bias": -4.035363744418628,
        "weights": {
          "0": -20.64290978292371,
          "1": 31.59086619000209,
          "2": 17.461509970798406,
          "3": 15.263479741757301,
          "4": 6.73024966101865,
          "5": -37.24036678213635
        }
      }
    }
  ],
  "outputLookup": true,
  "inputLookup": true
}

**Comment by thegamecat** [comment]
Then I pass in normalised data for each run. And each run comes out with the same do value.

**Comment by robertleeplummerjr** [comment]
How do you normalize data?

**Comment by thegamecat** [comment]
normalizedata: function (data) {
	var normdata = [];

    var min = Math.min(...data);
    var max = Math.max(...data);

    for (var i = 0; i < data.length; i++) {
      normdata[i] = (data[i]-min) / (max-min);
    }

    return normdata;
  },

**Comment by thegamecat** [comment]
Just to add, I've tried to make this simpler using only 1 and 0 inputs and got a much lower training error score and still I get:
{ input: 
   { ema20testema50: 1,
     ema20testema100: 0,
     ema20testema200: 0,
     ema50testema100: 0,
     ema50testema200: 0,
     ema100testema200: 0 } }
{ do: 0.013354765211227795 }
{ input: 
   { ema20testema50: 1,
     ema20testema100: 1,
     ema20testema200: 0,
     ema50testema100: 0,
     ema50testema200: 0,
     ema100testema200: 0 } }
{ do: 0.013354765211227795 }
{ input: 
   { ema20testema50: 1,
     ema20testema100: 1,
     ema20testema200: 0,
     ema50testema100: 0,
     ema50testema200: 0,
     ema100testema200: 0 } }
{ do: 0.013354765211227795 }
{ input: 
   { ema20testema50: 1,
     ema20testema100: 1,
     ema20testema200: 0,
     ema50testema100: 0,
     ema50testema200: 0,
     ema100testema200: 0 } }
{ do: 0.013354765211227795 }
{ input: 
   { ema20testema50: 1,
     ema20testema100: 1,
     ema20testema200: 1,
     ema50testema100: 0,
     ema50testema200: 0,
     ema100testema200: 0 } }
{ do: 0.013354765211227795 }
{ input: 
   { ema20testema50: 1,
     ema20testema100: 1,
     ema20testema200: 1,
     ema50testema100: 1,
     ema50testema200: 1,
     ema100testema200: 0 } }
{ do: 0.013354765211227795 }
{ input: 
   { ema20testema50: 1,
     ema20testema100: 1,
     ema20testema200: 1,
     ema50testema100: 1,
     ema50testema200: 1,
     ema100testema200: 1 } }
{ do: 0.013354765211227795 }

**Comment by robertleeplummerjr** [comment]
Can you throw the full reproduced issue in a jsfiddle or similar?

**Comment by robertleeplummerjr** [comment]
I believe this is resolved in [here](https://github.com/BrainJS/brain.js/pull/127) and is [released](https://github.com/BrainJS/brain.js/releases/tag/1.0.2) can you confirm?

**Comment by robertleeplummerjr** [comment]
ping

**Comment by rafaelxim** [comment]
not solved. I have the last 1.0.5 and I'm having the same issue. 

```

INPUTS:
{ mediaGolsFeitosCasa: 1.8,
  mediaGolsSofridosCasa: 0.8,
  mediaOddsCasa: 2.694,
  mediaGolsFeitosFora: 1,
  mediaGolsSofridosFora: 0.8,
  mediaOddsFora: 7.43 }

OUTPUTS:
{ Time1: 0.7227954268455505,
  Empate: 0.29719799757003784,
  Time2: 0.07673610746860504 }

INPUTS
{ mediaGolsFeitosCasa: 2.6,
  mediaGolsSofridosCasa: 2.8,
  mediaOddsCasa: 4.456,
  mediaGolsFeitosFora: 1.2,
  mediaGolsSofridosFora: 2.4,
  mediaOddsFora: 11.819999999999999 }

OUTPUTS
{ Time1: 0.7227954268455505,
  Empate: 0.29719799757003784,
  Time2: 0.07673610746860504 }

```

**Comment by rafaelxim** [comment]
```

for (var i=0, max=v.length; i < max; i++) {
				console.log(v[i]);
				output = net.run(v[i]);  
				console.log(output);	
			}
```

**Comment by robertleeplummerjr** [comment]
What activation are you using?

**Comment by mildrenben** [comment]
Hi @robertleeplummerjr I'm also having the same issue.

I have a repo here: https://github.com/mildrenben/brainjs-test

You can see it in action here: https://mildrenben.github.io/brainjs-test/index.html
(You will have to select each color twice before it'll move on. It console logs relevant info fyi)

Thanks

**Comment by robertleeplummerjr** [comment]
I think the issue here is normalization of data when using a sigmoid activation.  When I log your `savedData` (aka training data) I get this:
```js
JSON.stringify(savedData, null, 2)
```

Outputs: 
```json
[
  {
    "input": {
      "r": 168,
      "g": 163,
      "b": 225
    },
    "output": {
      "blue": 1
    }
  },
  {
    "input": {
      "r": 246,
      "g": 201,
      "b": 111
    },
    "output": {
      "orange": 1
    }
  },
  {
    "input": {
      "r": 35,
      "g": 60,
      "b": 156
    },
    "output": {
      "blue": 1
    }
  },
  {
    "input": {
      "r": 56,
      "g": 55,
      "b": 131
    },
    "output": {
      "purple": 1
    }
  },
  {
    "input": {
      "r": 169,
      "g": 172,
      "b": 233
    },
    "output": {
      "purple": 1
    }
  },
  {
    "input": {
      "r": 20,
      "g": 150,
      "b": 7
    },
    "output": {
      "green": 1
    }
  },
  {
    "input": {
      "r": 140,
      "g": 74,
      "b": 253
    },
    "output": {
      "purple": 1
    }
  },
  {
    "input": {
      "r": 135,
      "g": 9,
      "b": 157
    },
    "output": {
      "purple": 1
    }
  },
  {
    "input": {
      "r": 185,
      "g": 207,
      "b": 34
    },
    "output": {
      "green": 1
    }
  },
  {
    "input": {
      "r": 34,
      "g": 63,
      "b": 168
    },
    "output": {
      "blue": 1
    }
  },
  {
    "input": {
      "r": 204,
      "g": 42,
      "b": 101
    },
    "output": {
      "pink": 1
    }
  },
  {
    "input": {
      "r": 117,
      "g": 106,
      "b": 224
    },
    "output": {
      "purple": 1
    }
  },
  {
    "input": {
      "r": 154,
      "g": 115,
      "b": 62
    },
    "output": {
      "brown": 1
    }
  },
  {
    "input": {
      "r": 33,
      "g": 231,
      "b": 5
    },
    "output": {
      "green": 1
    }
  },
  {
    "input": {
      "r": 163,
      "g": 236,
      "b": 48
    },
    "output": {
      "green": 1
    }
  },
  {
    "input": {
      "r": 163,
      "g": 175,
      "b": 239
    },
    "output": {
      "blue": 1
    }
  }
]
```

You should normalize the values of input to values between 0 and 1.  If I run the following against the above data, all seems well:

train and modify input set to be between 0 and 1:
```
net.train(savedData.map(value => ({ input: { r: value.input.r / 255, g: value.input.g / 255, b: value.input.b / 255 }, output: value.output })));
```

which outputs:
```
{error: 0.017562830040200286, iterations: 20000}
```

Then when I go to run:
```
net.run({ r: 163 / 255, g: 175 / 255, b: 236 / 255 });
```

I get something more ideal:
```
{blue: 0.7469371557235718, orange: 0.0033875503577291965, purple: 0.10848929733037949, green: 0.0002883156994357705, pink: 2.855797731626808e-7, …}
```

**Comment by mildrenben** [comment]
@robertleeplummerjr Wow what a silly oversight from me. Thanks so much for figuring that out, I would've never got that! Thanks!

**Comment by robertleeplummerjr** [comment]
We're all in this together ;)
No worries.

**Comment by robertleeplummerjr** [comment]
Close-worthy guys?

**Comment by LegendOfGIT** [comment]
Close this “issue" ^^
